name: Setup Node & pnpm
description: Setup pnpm, install Node.js, and install dependencies
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
    - name: Install dependencies
      shell: bash
      run: pnpm install --no-frozen-lockfile
