name: e2e tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: e2e:${{ github.ref }}

env:
  CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  VITE_CONVEX_URL: ${{ secrets.VITE_CONVEX_URL }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm & Node.js
        uses: ./.github/actions/setup-node-pnpm

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run tests
        run: npm test
