name: Format

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm & Node.js
        uses: ./.github/actions/setup-node-pnpm

      - name: Format
        uses: mathiasvr/command-output@v2.0.0
        id: format
        with:
          run: pnpm run format-unsafe

      - name: Create pull request
        if: ${{ always() }}
        uses: peter-evans/create-pull-request@v6
        with:
          title: Format code
          commit-message: format
          body: |
            Runs Prettier and applies unsafe fixes from Biome.
            ```
            ${{ steps.format.outputs.stdout }}
            ```
          branch: ci-format
          delete-branch: true
